# Generated by Django 4.1.2 on 2023-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='testimony',
            field=models.TextField(max_length=500),
        ),
    ]
