# Generated by Django 4.1.2 on 2023-08-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_feedback_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='testimony',
            field=models.TextField(max_length=5000),
        ),
    ]
