# Generated by Django 4.1.2 on 2023-03-01 11:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('pending_deposit_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('pending_deposit', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Deposit Amount')),
                ('tokens', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'BNB')], default='ETH', max_length=4)),
                ('comparator_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('comparator', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1.0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1), djmoney.models.validators.MaxMoneyValidator(1)], verbose_name='comparator')),
                ('accountUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Balance')),
                ('pending_transfer_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('pending_transfer', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Pending Transfer')),
                ('approved_deposit_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('approved_deposit', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Approved Deposit')),
                ('approved_withdrawal_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('approved_withdrawal', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Aprroved_withdrawal')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pending_withdrawal_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('pending_withdrawal', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Withdrawal Amount')),
                ('profit_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('profit', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Profit')),
                ('notification_deposit', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notification_transfer', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notification_withdrawal', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('wallet_address', models.CharField(max_length=300)),
                ('restriction', models.BooleanField(default=False)),
                ('identity_number', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=19, null=True, verbose_name='Amount')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
            ],
        ),
    ]
