# Generated by Django 4.1.2 on 2023-03-01 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Wallet address', max_length=200, null=True)),
                ('btc', models.CharField(blank=True, max_length=400, null=True, verbose_name='Bitcoin')),
                ('eth', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ethereum')),
                ('usdt', models.CharField(blank=True, max_length=400, null=True, verbose_name='Usdt')),
                ('bnb', models.CharField(blank=True, max_length=400, null=True, verbose_name='Bnb')),
                ('logo_btc', models.FileField(blank=True, null=True, upload_to='images/')),
                ('logo_eth', models.FileField(blank=True, null=True, upload_to='images/')),
                ('logo_usdt', models.FileField(blank=True, null=True, upload_to='images/')),
                ('logo_bnb', models.FileField(blank=True, null=True, upload_to='images/')),
                ('qr_code_btc', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('qr_code_eth', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('qr_code_usdt', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('qr_code_bnb', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
            ],
        ),
    ]
