# Generated by Django 4.1.2 on 2023-03-01 14:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_walletinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='approved_deposit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Approved Deposit'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='approved_deposit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='approved_withdrawal',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Aprroved_withdrawal'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='approved_withdrawal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='comparator',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('1.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(1), djmoney.models.validators.MaxMoneyValidator(1)], verbose_name='comparator'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='comparator_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='notification_deposit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='notification_transfer',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='notification_withdrawal',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_deposit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_deposit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_transfer',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Pending Transfer'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_transfer_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_withdrawal',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Withdrawal Amount'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_withdrawal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
