# Generated by Django 4.1.2 on 2023-03-01 14:58

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboard_approved_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='approved_deposit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Approved Deposit'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='approved_withdrawal',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Aprroved_withdrawal'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_deposit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='pending_withdrawal',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Withdrawal Amount'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='profit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Profit'),
        ),
    ]
