# Generated by Django 4.1.2 on 2023-03-01 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_alter_walletinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='walletinformation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
